services:
  db:
    image: mongo:8.0
    container_name: pdf_mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

  app:
      build: .
      container_name: pdf_api_app
      ports:
        - "8000:8000"
      depends_on:
        - db
      environment:
        # PISAMOS el valor del .env para que la APP use el nombre del servicio 'db'
        - MONGO_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db:27017

# Definición del volumen para que los datos no se pierdan
volumes:
  mongo_data: